export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE="GET_PRODUCTS_FAILURE";

//posting advertise/data
export const POSTDATA_REQUEST="POSTDATA_REQUEST";
export const POSTDATA_SUCCESS="POSTDATA_SUCCESS";
export const POSTDATA_FAILURE="POSTDATA_FAILURE";